In [6]:
import numpy as np

arr = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr)

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [4]:
import numpy as np

arr = np.array(42)
print(arr.shape)

()


In [10]:
arr = np.random.randn(2,3)
arr

array([[-0.94662797,  1.73913145, -1.64424815],
       [ 1.08716242,  0.03092276, -0.74966374]])

In [13]:
arr = np.random.rand(2,3)
arr

array([[0.11705545, 0.5227535 , 0.90090653],
       [0.07912096, 0.00203998, 0.8199477 ]])

In [23]:
arr = np.random.randn(2,3)
arr

array([[ 0.77729158, -0.68070138,  0.13599825],
       [-0.2686488 , -1.12704453, -0.31410213]])

In [15]:
arr.shape

(2, 3)

In [25]:
arr =arr.reshape(6)
print(arr)

[ 0.77729158 -0.68070138  0.13599825 -0.2686488  -1.12704453 -0.31410213]
